apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: foo
build:
  artifacts:
    - image: pedrozena/foo
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - deployment-foo.yml